0426/06_django_with_AJAX/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.password_change, name='password_change'),
    path('update/', views.update, name='update'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

0426/06_django_with_AJAX/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

0426/06_django_with_AJAX/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'last_name', 'first_name')

0426/06_django_with_AJAX/accounts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST, require_safe, require_http_methods
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.http import JsonResponse

User = get_user_model()

# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

@require_POST
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

@require_POST
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('accounts:login')

@require_http_methods(['GET', 'POST'])
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'accounts/change_password.html', context)

@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form': form}
    return render(request, 'accounts/update.html', context)

@require_safe
def profile(request, username):
    user = User.objects.get(username=username)
    context = {
        'user': user
    }
    return render(request, 'accounts/profile.html', context)

@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        me = request.user
        you = User.objects.get(pk=user_pk)
        if me != you:
            if you.followers.filter(pk=me.pk).exists():
                you.followers.remove(me)
                is_followed = False
            else:
                you.followers.add(me)
                is_followed = True

            followerscnt = you.followers.count()
            followingscnt = you.followings.count()

            context = {
                'is_followed':is_followed,
                'followerscnt':followerscnt,
                'followingscnt':followingscnt,
            }
            return JsonResponse(context)
    else:
        return redirect('accounts:login')

0426/06_django_with_AJAX/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
  <h1>비밀번호변경</h1>
  <form action="{% url 'accounts:password_change' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="변경하기">
  </form>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

0426/06_django_with_AJAX/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>Login</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="로그인">
  </form>
{% endblock content %}

0426/06_django_with_AJAX/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
  <h1>{{ user.username }}님의 프로필</h1>
  <div>
    <div>
      팔로잉 :
      <span id="followingscnt">{{ user.followings.count }}</span>
      팔로워 :
      <span id="followerscnt">{{ user.followers.count }}</span>
    </div>
    {% if request.user != user %}
      <form id="follow_form" data-user-id="{{ user.pk }}">
        {% csrf_token %}
        <!--지금 현재 상태를 제공하는 것-->
        {% if request.user in user.followers.all %}
          <button type="submit" class="btn btn-danger">언팔로우</button>
        {% else %}
          <button type="submit" class="btn btn-primary">팔로우</button>
        {% endif %}
      </form>
    {% endif %}
  </div>
  <hr/>

  <h5>{{ user.username }}님의 작성글</h5>
  <hr/>
  {% for article in user.article_set.all %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <p class="card-text">{{ article.content }}</p>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">자세히 보기</a>
      </div>
    </div>
  {% endfor %}
  <br/><br/>

  <h5>{{ user.username }}님이 좋아요한 게시물</h5>
  <hr/>
  {% for article in user.like_articles.all %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ article.title }}</h5>
        <p class="card-text">{{ article.content }}</p>
        <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">자세히 보기</a>
      </div>
    </div>
  {% endfor %}

  <br/><br/>
  <a href="{% url 'articles:index' %}" class="btn btn-success">목록보기</a>

{% endblock content %}
{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    // 1. 팔로우 버튼을 특정해서 클릭 할 수 있어야한다.
    const form = document.querySelector("#follow_form");
    const csrftoken = document
      .querySelector("[name=csrfmiddlewaretoken]")
      .value;
    const followBtn = document.querySelector("#follow_form > button");

    // follow cnt
    const FollowersCnt = document.querySelector("#followerscnt");
    const FollowingsCnt = document.querySelector("#followingscnt");

    form.addEventListener("submit", function (event) {
      event.preventDefault();
      const userId = event.target.dataset.userId;

      followBtn
        .classList
        .toggle("btn-danger");
      followBtn
        .classList
        .toggle("btn-primary");

      axios({
        method: "post",
        url: `http://127.0.0.1:8000/accounts/${userId}/follow/`,
        headers: {
          "X-CSRFToken": csrftoken
        }
      }).then((response) => {
        const isFollowed = response.data.is_followed;

        // 팔로 숫자 실시간
        FollowersCnt.innerText = response.data.followerscnt;
        FollowingsCnt.innerText = response.data.followingscnt;

        if (isFollowed === true) {
          // 이미 팔로우되어있으니 언팔해야됨
          followBtn.innerText = "언팔로우";

          console.log("언팔로우");
        } else {
          followBtn.innerText = "팔로우";
          console.log("팔로우");
        }
      });
    });
    // 2. 클릭 (혹은 제출) 이벤트가 발생했을때 어떠한 함수가 실행 되도록 해야한다.
    // form의 기본 이벤트 전파 방지 (action으로 요청 보내는 것 막기)
    // axios로 요청 보내기 -> follow
    // url = `${user.pk}` 쓸 수 없다.
  </script>
{% endblock script %}

0426/06_django_with_AJAX/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="회원가입">
  </form>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

0426/06_django_with_AJAX/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원정보수정</h1>
  <form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="수정하기">
  </form>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}